source 'https://rubygems.org'

# Web
gem 'puma'           , '~> 6.4'
gem 'sinatra'        , '~> 3.2'
gem 'sinatra-contrib', '~> 3.2' # includes automatic code reloader for dev

# Debug
group :development, :test do
  gem 'pry-byebug', '~> 3.10'
end
